### PR TITLE
Add BruNix, the Brussels Nix User Group

### PR DESCRIPTION
**Pull request by michaelshmitty**

### CODE REVIEW

**Comment by michaelshmitty** [comment]
Waiting for location confirmation to go into the "TBD".

**Comment by MatthewCroughan** [comment]
I'm in Brussels right now, but will be going home tomorrow, so will miss this, shame! :D

**Comment by michaelshmitty** [comment]
> I'm in Brussels right now, but will be going home tomorrow, so will miss this, shame! :D

Ah no worries, we're gonna keep this going and hopefully next time you're in Brussels you can join. Saw the NixOS on mobile demo you showed at FOSDEM and Bytenight, nice one! And thanks for your YouTube videos regarding Nix, I found them super informative and helpful when I got started with this! Safe travels, see you soon!

**Comment by michaelshmitty** [comment]
We've got a confirmation on location so this is good to go. Cheers for building this!

**Review by MatthewCroughan — APPROVED** [review]

**Pull request merged**
