### PR TITLE
added logo

### PR DESCRIPTION
**Pull request by transgirllucy**

### CODE REVIEW

**Comment by MatthewCroughan** [comment]
The SVG is not the right size, it is much larger, look at the GitHub preview

**Comment by MatthewCroughan** [comment]
There's also a missing semicolon. If you want to preview the site then just `nix run .#serve`

**Comment by transgirllucy** [comment]
> The SVG is not the right size, it is much larger, look at the GitHub preview

i will refactor it

**Comment by MatthewCroughan** [comment]
The SVG needs to have a 1:1 aspect ratio

**Comment by transgirllucy** [comment]
> The SVG needs to have a 1:1 aspect ratio

i will add the logo later

**Pull request closed without merging**
